### ISSUE TITLE
Option to disable VANILLA enchantments.

### ISSUE THREAD

**Issue by K0-RR** [Jamalam360/ExcessEnchantments#2]
I hate fortune. Would you be interested in adding a option to backlist vanilla enchantments?

**Comment by Jamalam360** [comment]
I'll look into it.

**Comment by Jamalam360** [comment]
I've had a think about this. I'll likely be making some kind of library for enchantments since it seems I'll be working on this enchantments mod for a while. So the answer is, possibly, but likely not natively in this mod, rather in a library that this mod uses. I'm going to close this issue, thanks for the suggestion
